### ISSUE TITLE
huhu

### ISSUE THREAD

**Issue by Stricted** [florianprobst/ips-speedport#1]
schönes projekt, sollte in meiner api etwas wichtiges fehlen sag gerne bescheid :)

**Comment by florianprobst** [comment]
Hi, danke für das Angebot :-)
Ich bin in GitHub noch nicht so firm. Hoffe ich hab alles richtig gemacht mit dem Integrieren deines Codes.

Bei meiner bisherigen Version (Screenshots) ging alles wunderbar. Aber ich möchte nun einige weitere Methoden einführen. Deshalb bin ich dabei das Skript neu zu strukturieren und auf GitHub zu bringen. Dabei ist mir aufgefallen, dass deine neue Version ja extrem weiterentwickelt wurde im Vergleich zur letzten. Super! Geht die neue Version auch schon mit der neusten Firmware des Routers? Da hat die Telekom soweit ich weiß Änderungen an der Oberfläche vorgenommen. (FW:  050124.02.00.009)

**Comment by Stricted** [comment]
moin jep soweit passt alles :)

ja es ist mit der neuesten version der router firmware kompatibel (habe die 050124.02.00.009 selber auf meinem router), ich arbeite hin und wieder an der api daher die weiterentwicklung ;)

wegen der schönheit mach dir keine sorgen ^^ ich mag es nur wenn mein code übersichtlich und aufgeräumt ist daher auch die auftrennung mittels traits in einzelne datein, das macht das ganze übersichtlicher

die api selber ist auh mehr oder weniger aus langeweile entstanden und hat sich mit der zeit weiterentwickelt, mein ziel ist es am ende alle funktionen die der router hat mittels php ansteuern zu können (mit geht das webinterfae so dermaßen auf dem sack das glaubst du kaum (blödes tonnenweise javascript gedönse da)) 

solltest du fragen haben einfach fragen, gerne auch per email

MfG
Stricted

**Comment by Stricted** [comment]
https://github.com/florianprobst/ips-speedport/blob/master/IPSSpeedportHybrid.class.php#L325 das hättest du nicht gebraucht dashier macht in grunde genau das gleiche https://github.com/Stricted/speedport-hybrid-php-api/blob/master/SpeedportHybrid.class.php#L54
nur das du nicht explizit danach suchen musst
