### ISSUE TITLE
speedport kompatibilität

### ISSUE THREAD

**Issue by Stricted** [florianprobst/ips-speedport#3]
moin moin
in deiner readme kannst du folgendes streichen
"Ältere Speedportmodelle verfügen über ein anderes Webinterface / Anmeldeverfahren und funktionieren voraussichtlich nicht. Eventuell funktioniert es mit aktuellen Non-Hybrid-Speedports."

ich habe mir alle speedports angeschaut die infrage kommen würden und habe festgestellt das alle ein anderes anmeldeverfahren haben (ich habe die firmware entpackt und mir alles relevante angeschaut)

mit dem speedport w724v könnte das ganze klappen sofern man die login methoden anpasst (habe es mir sonst nicht weiter angeschaut aber viele .json entpunkte sind vorhanden)

**Comment by florianprobst** [comment]
Danke für den Hinweis. Hab's angepasst.
